import { AppState } from './types';

// Generate mock data for the application
const now = new Date();
const oneWeekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
const oneMonthAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);

export const mockData: AppState = {
  currentUser: {
    id: 'user-1',
    name: 'Ana García',
    email: 'ana.garcia@empresa.com',
    role: 'manager',
    teams: ['team-1', 'team-2'],
    lastSeen: now,
    isOnline: true,
  },
  
  users: [
    {
      id: 'user-1',
      name: 'Ana García',
      email: 'ana.garcia@empresa.com',
      role: 'manager',
      teams: ['team-1', 'team-2'],
      lastSeen: now,
      isOnline: true,
    },
    {
      id: 'user-2',
      name: 'Carlos López',
      email: 'carlos.lopez@empresa.com',
      role: 'member',
      teams: ['team-1'],
      lastSeen: new Date(now.getTime() - 5 * 60 * 1000), // 5 minutes ago
      isOnline: true,
    },
    {
      id: 'user-3',
      name: 'María Rodríguez',
      email: 'maria.rodriguez@empresa.com',
      role: 'member',
      teams: ['team-1', 'team-3'],
      lastSeen: new Date(now.getTime() - 30 * 60 * 1000), // 30 minutes ago
      isOnline: false,
    },
    {
      id: 'user-4',
      name: 'David Martín',
      email: 'david.martin@empresa.com',
      role: 'admin',
      teams: ['team-2', 'team-3'],
      lastSeen: new Date(now.getTime() - 2 * 60 * 1000), // 2 minutes ago
      isOnline: true,
    },
    {
      id: 'user-5',
      name: 'Laura Sánchez',
      email: 'laura.sanchez@empresa.com',
      role: 'member',
      teams: ['team-2'],
      lastSeen: new Date(now.getTime() - 15 * 60 * 1000), // 15 minutes ago
      isOnline: false,
    },
  ],
  
  teams: [
    {
      id: 'team-1',
      name: 'Desarrollo Frontend',
      description: 'Equipo encargado del desarrollo de interfaces de usuario',
      members: ['user-1', 'user-2', 'user-3'],
      projects: ['project-1', 'project-2'],
      createdAt: oneMonthAgo,
      color: '#3B82F6',
    },
    {
      id: 'team-2',
      name: 'Marketing Digital',
      description: 'Equipo de marketing y comunicación digital',
      members: ['user-1', 'user-4', 'user-5'],
      projects: ['project-3'],
      createdAt: oneMonthAgo,
      color: '#10B981',
    },
    {
      id: 'team-3',
      name: 'Backend & DevOps',
      description: 'Infraestructura y desarrollo backend',
      members: ['user-3', 'user-4'],
      projects: ['project-4'],
      createdAt: new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000),
      color: '#8B5CF6',
    },
  ],
  
  projects: [
    {
      id: 'project-1',
      name: 'Plataforma E-commerce',
      description: 'Desarrollo de nueva plataforma de comercio electrónico',
      teamId: 'team-1',
      status: 'active',
      priority: 'high',
      startDate: oneMonthAgo,
      endDate: new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000),
      progress: 65,
      tasks: ['task-1', 'task-2', 'task-3'],
      files: ['file-1', 'file-2'],
      createdAt: oneMonthAgo,
    },
    {
      id: 'project-2',
      name: 'App Mobile',
      description: 'Aplicación móvil para clientes',
      teamId: 'team-1',
      status: 'planning',
      priority: 'medium',
      startDate: new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000),
      progress: 10,
      tasks: ['task-4'],
      files: ['file-3'],
      createdAt: oneWeekAgo,
    },
    {
      id: 'project-3',
      name: 'Campaña Q4',
      description: 'Campaña de marketing para el cuarto trimestre',
      teamId: 'team-2',
      status: 'active',
      priority: 'high',
      startDate: oneWeekAgo,
      endDate: new Date(now.getTime() + 60 * 24 * 60 * 60 * 1000),
      progress: 40,
      tasks: ['task-5', 'task-6'],
      files: ['file-4'],
      createdAt: oneWeekAgo,
    },
    {
      id: 'project-4',
      name: 'Migración Cloud',
      description: 'Migración de infraestructura a la nube',
      teamId: 'team-3',
      status: 'on-hold',
      priority: 'low',
      startDate: oneMonthAgo,
      progress: 25,
      tasks: ['task-7'],
      files: [],
      createdAt: oneMonthAgo,
    },
  ],
  
  tasks: [
    {
      id: 'task-1',
      title: 'Diseño de la página de inicio',
      description: 'Crear wireframes y mockups de la página principal',
      projectId: 'project-1',
      assigneeId: 'user-2',
      status: 'completed',
      priority: 'high',
      dueDate: oneWeekAgo,
      createdAt: oneMonthAgo,
      updatedAt: oneWeekAgo,
      tags: ['design', 'ui'],
      attachments: ['file-1'],
    },
    {
      id: 'task-2',
      title: 'Implementación del carrito',
      description: 'Desarrollar funcionalidad del carrito de compras',
      projectId: 'project-1',
      assigneeId: 'user-3',
      status: 'in-progress',
      priority: 'high',
      dueDate: new Date(now.getTime() + 3 * 24 * 60 * 60 * 1000),
      createdAt: oneWeekAgo,
      updatedAt: now,
      tags: ['development', 'frontend'],
      attachments: [],
    },
    {
      id: 'task-3',
      title: 'Testing de pagos',
      description: 'Probar integración con pasarelas de pago',
      projectId: 'project-1',
      assigneeId: 'user-1',
      status: 'todo',
      priority: 'medium',
      dueDate: new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000),
      createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000),
      updatedAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000),
      tags: ['testing', 'payments'],
      attachments: [],
    },
    {
      id: 'task-4',
      title: 'Investigación UX',
      description: 'Investigar mejores prácticas para apps móviles',
      projectId: 'project-2',
      status: 'in-progress',
      priority: 'low',
      createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000),
      updatedAt: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000),
      tags: ['research', 'ux'],
      attachments: [],
    },
    {
      id: 'task-5',
      title: 'Contenido para redes sociales',
      description: 'Crear contenido para Facebook e Instagram',
      projectId: 'project-3',
      assigneeId: 'user-5',
      status: 'review',
      priority: 'medium',
      dueDate: new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000),
      createdAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000),
      updatedAt: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000),
      tags: ['content', 'social'],
      attachments: ['file-4'],
    },
    {
      id: 'task-6',
      title: 'Análisis de competencia',
      description: 'Estudiar estrategias de la competencia',
      projectId: 'project-3',
      assigneeId: 'user-4',
      status: 'completed',
      priority: 'medium',
      createdAt: oneWeekAgo,
      updatedAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000),
      tags: ['analysis', 'research'],
      attachments: [],
    },
    {
      id: 'task-7',
      title: 'Setup AWS',
      description: 'Configurar infraestructura inicial en AWS',
      projectId: 'project-4',
      assigneeId: 'user-4',
      status: 'todo',
      priority: 'low',
      createdAt: oneMonthAgo,
      updatedAt: oneMonthAgo,
      tags: ['devops', 'cloud'],
      attachments: [],
    },
  ],
  
  channels: [
    {
      id: 'channel-1',
      name: 'General Frontend',
      type: 'group',
      participants: ['user-1', 'user-2', 'user-3'],
      teamId: 'team-1',
      lastMessage: 'Perfecto, mañana revisamos el pull request',
      lastMessageAt: new Date(now.getTime() - 30 * 60 * 1000),
      createdAt: oneMonthAgo,
    },
    {
      id: 'channel-2',
      name: 'Proyecto E-commerce',
      type: 'project',
      participants: ['user-1', 'user-2', 'user-3'],
      projectId: 'project-1',
      lastMessage: 'El carrito ya está funcionando correctamente',
      lastMessageAt: new Date(now.getTime() - 2 * 60 * 60 * 1000),
      createdAt: oneMonthAgo,
    },
    {
      id: 'channel-3',
      name: 'Ana & Carlos',
      type: 'direct',
      participants: ['user-1', 'user-2'],
      lastMessage: '¿Puedes revisar el diseño cuando tengas un momento?',
      lastMessageAt: new Date(now.getTime() - 15 * 60 * 1000),
      createdAt: oneWeekAgo,
    },
  ],
  
  messages: [
    {
      id: 'msg-1',
      content: 'Hola equipo, ¿cómo van con el proyecto?',
      senderId: 'user-1',
      channelId: 'channel-1',
      type: 'text',
      timestamp: new Date(now.getTime() - 2 * 60 * 60 * 1000),
      readBy: [
        { userId: 'user-1', readAt: new Date(now.getTime() - 2 * 60 * 60 * 1000) },
        { userId: 'user-2', readAt: new Date(now.getTime() - 1 * 60 * 60 * 1000) },
        { userId: 'user-3', readAt: new Date(now.getTime() - 45 * 60 * 1000) },
      ],
    },
    {
      id: 'msg-2',
      content: 'Todo bien por aquí, el carrito ya está funcionando correctamente',
      senderId: 'user-3',
      channelId: 'channel-2',
      type: 'text',
      timestamp: new Date(now.getTime() - 2 * 60 * 60 * 1000),
      readBy: [
        { userId: 'user-3', readAt: new Date(now.getTime() - 2 * 60 * 60 * 1000) },
        { userId: 'user-1', readAt: new Date(now.getTime() - 1 * 60 * 60 * 1000) },
      ],
    },
    {
      id: 'msg-3',
      content: '¿Puedes revisar el diseño cuando tengas un momento?',
      senderId: 'user-2',
      channelId: 'channel-3',
      type: 'text',
      timestamp: new Date(now.getTime() - 15 * 60 * 1000),
      readBy: [
        { userId: 'user-2', readAt: new Date(now.getTime() - 15 * 60 * 1000) },
      ],
    },
    {
      id: 'msg-4',
      content: 'Perfecto, mañana revisamos el pull request',
      senderId: 'user-1',
      channelId: 'channel-1',
      type: 'text',
      timestamp: new Date(now.getTime() - 30 * 60 * 1000),
      readBy: [
        { userId: 'user-1', readAt: new Date(now.getTime() - 30 * 60 * 1000) },
        { userId: 'user-2', readAt: new Date(now.getTime() - 25 * 60 * 1000) },
      ],
    },
  ],
  
  files: [
    {
      id: 'file-1',
      name: 'homepage-mockup.png',
      size: 2048576, // 2MB
      type: 'image/png',
      url: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAwIiBoZWlnaHQ9IjYwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjZGRkIi8+PHRleHQgeD0iNTAlIiB5PSI1MCUiIGZvbnQtc2l6ZT0iMTgiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuM2VtIj5Ib21lcGFnZSBNb2NrdXAgRGVzaWduPC90ZXh0Pjwvc3ZnPg==',
      uploaderId: 'user-2',
      uploadedAt: oneWeekAgo,
      projectId: 'project-1',
      taskId: 'task-1',
    },
    {
      id: 'file-2',
      name: 'requirements.pdf',
      size: 1024768, // 1MB
      type: 'application/pdf',
      url: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAwIiBoZWlnaHQ9IjMwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjZGRkIi8+PHRleHQgeD0iNTAlIiB5PSI1MCUiIGZvbnQtc2l6ZT0iMTgiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuM2VtIj5Qcm9qZWN0IFJlcXVpcmVtZW50cyBEb2N1bWVudDwvdGV4dD48L3N2Zz4=',
      uploaderId: 'user-1',
      uploadedAt: oneMonthAgo,
      projectId: 'project-1',
    },
    {
      id: 'file-3',
      name: 'mobile-wireframes.fig',
      size: 5242880, // 5MB
      type: 'application/figma',
      url: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjAwIiBoZWlnaHQ9IjQwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjZGRkIi8+PHRleHQgeD0iNTAlIiB5PSI1MCUiIGZvbnQtc2l6ZT0iMTgiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuM2VtIj5Nb2JpbGUgQXBwIFdpcmVmcmFtZXM8L3RleHQ+PC9zdmc+',
      uploaderId: 'user-3',
      uploadedAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000),
      projectId: 'project-2',
    },
    {
      id: 'file-4',
      name: 'campaign-assets.zip',
      size: 15728640, // 15MB
      type: 'application/zip',
      url: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAwIiBoZWlnaHQ9IjMwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjZGRkIi8+PHRleHQgeD0iNTAlIiB5PSI1MCUiIGZvbnQtc2l6ZT0iMTgiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuM2VtIj5NYXJrZXRpbmcgQ2FtcGFpZ24gQXNzZXRzPC90ZXh0Pjwvc3ZnPg==',
      uploaderId: 'user-5',
      uploadedAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000),
      projectId: 'project-3',
      taskId: 'task-5',
    },
  ],
  
  notifications: [
    {
      id: 'notif-1',
      userId: 'user-1',
      type: 'task_assigned',
      title: 'Nueva tarea asignada',
      content: 'Se te ha asignado la tarea "Testing de pagos"',
      read: false,
      createdAt: new Date(now.getTime() - 2 * 60 * 60 * 1000),
      actionUrl: '/projects',
      metadata: { taskId: 'task-3', projectId: 'project-1' },
    },
    {
      id: 'notif-2',
      userId: 'user-1',
      type: 'message',
      title: 'Nuevo mensaje',
      content: 'Carlos López: ¿Puedes revisar el diseño cuando tengas un momento?',
      read: false,
      createdAt: new Date(now.getTime() - 15 * 60 * 1000),
      actionUrl: '/chat',
      metadata: { channelId: 'channel-3', messageId: 'msg-3' },
    },
    {
      id: 'notif-3',
      userId: 'user-1',
      type: 'project_update',
      title: 'Actualización de proyecto',
      content: 'El progreso del proyecto "Plataforma E-commerce" se actualizó al 65%',
      read: true,
      createdAt: new Date(now.getTime() - 4 * 60 * 60 * 1000),
      actionUrl: '/projects',
      metadata: { projectId: 'project-1' },
    },
  ],
  
  sidebarCollapsed: false,
};