version: '3.8'

services:
  teamwork-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/projects"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Base de datos (opcional - descomenta si usas PostgreSQL)
  # db:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: teamwork
  #     POSTGRES_USER: teamwork_user
  #     POSTGRES_PASSWORD: secure_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

  # Redis para cache (opcional)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped

# volumes:
#   postgres_data: